//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WXYZ_Hotel.SpecialTours {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="STOLXMLAllocationSoap", Namespace="http://b2b.stglobe.com/STOLXMLAllocation")]
    public partial class STOLXMLAllocation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ServiceStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllocationSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllocationSearchHLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public STOLXMLAllocation() {
            this.Url = global::WXYZ_Hotel.Properties.Settings.Default.WXYZ_Hotel_SpecialTours_STOLXMLAllocation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ServiceStatusCompletedEventHandler ServiceStatusCompleted;
        
        /// <remarks/>
        public event AllocationSearchCompletedEventHandler AllocationSearchCompleted;
        
        /// <remarks/>
        public event AllocationSearchHLCompletedEventHandler AllocationSearchHLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://b2b.stglobe.com/STOLXMLAllocation/ServiceStatus", RequestNamespace="http://b2b.stglobe.com/STOLXMLAllocation", ResponseNamespace="http://b2b.stglobe.com/STOLXMLAllocation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ServiceStatus() {
            object[] results = this.Invoke("ServiceStatus", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ServiceStatusAsync() {
            this.ServiceStatusAsync(null);
        }
        
        /// <remarks/>
        public void ServiceStatusAsync(object userState) {
            if ((this.ServiceStatusOperationCompleted == null)) {
                this.ServiceStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceStatusOperationCompleted);
            }
            this.InvokeAsync("ServiceStatus", new object[0], this.ServiceStatusOperationCompleted, userState);
        }
        
        private void OnServiceStatusOperationCompleted(object arg) {
            if ((this.ServiceStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceStatusCompleted(this, new ServiceStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://b2b.stglobe.com/STOLXMLAllocation/AllocationSearch", RequestNamespace="http://b2b.stglobe.com/STOLXMLAllocation", ResponseNamespace="http://b2b.stglobe.com/STOLXMLAllocation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AllocationSearch(string pXML) {
            object[] results = this.Invoke("AllocationSearch", new object[] {
                        pXML});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AllocationSearchAsync(string pXML) {
            this.AllocationSearchAsync(pXML, null);
        }
        
        /// <remarks/>
        public void AllocationSearchAsync(string pXML, object userState) {
            if ((this.AllocationSearchOperationCompleted == null)) {
                this.AllocationSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllocationSearchOperationCompleted);
            }
            this.InvokeAsync("AllocationSearch", new object[] {
                        pXML}, this.AllocationSearchOperationCompleted, userState);
        }
        
        private void OnAllocationSearchOperationCompleted(object arg) {
            if ((this.AllocationSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllocationSearchCompleted(this, new AllocationSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://b2b.stglobe.com/STOLXMLAllocation/AllocationSearchHL", RequestNamespace="http://b2b.stglobe.com/STOLXMLAllocation", ResponseNamespace="http://b2b.stglobe.com/STOLXMLAllocation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AllocationSearchHL(string pXML) {
            object[] results = this.Invoke("AllocationSearchHL", new object[] {
                        pXML});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AllocationSearchHLAsync(string pXML) {
            this.AllocationSearchHLAsync(pXML, null);
        }
        
        /// <remarks/>
        public void AllocationSearchHLAsync(string pXML, object userState) {
            if ((this.AllocationSearchHLOperationCompleted == null)) {
                this.AllocationSearchHLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllocationSearchHLOperationCompleted);
            }
            this.InvokeAsync("AllocationSearchHL", new object[] {
                        pXML}, this.AllocationSearchHLOperationCompleted, userState);
        }
        
        private void OnAllocationSearchHLOperationCompleted(object arg) {
            if ((this.AllocationSearchHLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllocationSearchHLCompleted(this, new AllocationSearchHLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ServiceStatusCompletedEventHandler(object sender, ServiceStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AllocationSearchCompletedEventHandler(object sender, AllocationSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllocationSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllocationSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AllocationSearchHLCompletedEventHandler(object sender, AllocationSearchHLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllocationSearchHLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllocationSearchHLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591